/**
 * The strategy definition language.
 *
 * A strategy is plain JSON: a list of indicators to compute, boolean conditions
 * built over them, and the risk/sizing rules that turn a signal into a position.
 * Being data rather than code means strategies can be saved, shared, diffed,
 * generated by a UI form, and round-tripped through a file without an eval().
 */

import type { PriceField } from "./types";

/** An indicator to compute once up front and reference by `id` in conditions. */
export type IndicatorSpec =
  | { id: string; type: "sma"; period: number; source?: PriceField }
  | { id: string; type: "ema"; period: number; source?: PriceField }
  | { id: string; type: "rsi"; period: number; source?: PriceField }
  | { id: string; type: "atr"; period: number }
  | { id: string; type: "adx"; period: number }
  | { id: string; type: "plusDI"; period: number }
  | { id: string; type: "minusDI"; period: number }
  | {
      id: string;
      type: "macd";
      fast: number;
      slow: number;
      signal: number;
      output: "macd" | "signal" | "histogram";
      source?: PriceField;
    }
  | {
      id: string;
      type: "bbands";
      period: number;
      stdDev: number;
      output: "upper" | "middle" | "lower";
      source?: PriceField;
    }
  | { id: string; type: "stoch"; kPeriod: number; smooth: number; dPeriod: number; output: "k" | "d" }
  | {
      id: string;
      type: "supertrend";
      period: number;
      multiplier: number;
      /** "line" is the trailing stop level; "direction" is +1 up, -1 down. */
      output: "line" | "direction";
    }
  | { id: string; type: "highest"; period: number; source?: PriceField }
  | { id: string; type: "lowest"; period: number; source?: PriceField };

export type Operand =
  | { kind: "indicator"; id: string }
  | { kind: "price"; field: PriceField }
  | { kind: "const"; value: number };

export type Condition =
  | { type: "gt" | "gte" | "lt" | "lte"; left: Operand; right: Operand }
  | { type: "crossesAbove" | "crossesBelow"; left: Operand; right: Operand }
  | { type: "and" | "or"; children: Condition[] }
  | { type: "not"; child: Condition }
  | { type: "always" };

/** How far the stop sits from entry. */
export type StopSpec =
  | { mode: "pips"; value: number }
  | { mode: "percent"; value: number }
  | { mode: "atr"; multiple: number; atrId: string };

/** How far the target sits from entry. `riskReward` is a multiple of stop distance. */
export type TargetSpec = StopSpec | { mode: "riskReward"; ratio: number };

export type SizingSpec =
  | { mode: "fixedLot"; lots: number }
  /** Risk a fixed fraction of current equity per trade. Requires a stop loss. */
  | { mode: "riskPercent"; percent: number };

export interface SideRules {
  entry: Condition;
  /** Optional rule-based exit, checked alongside stop/target on every bar. */
  exit?: Condition;
}

export interface Strategy {
  name: string;
  description?: string;
  indicators: IndicatorSpec[];
  long?: SideRules;
  short?: SideRules;
  stopLoss?: StopSpec;
  takeProfit?: TargetSpec;
  /** Ratchets the stop in the trade's favour; never moves against the position. */
  trailingStop?: StopSpec;
  sizing: SizingSpec;
  /** Force-close a position that has been open this many bars. */
  maxBarsInTrade?: number;
  /** Restrict entries to a UTC hour window, half-open: [startHour, endHour). */
  sessionUtc?: { startHour: number; endHour: number };
  /** Bars to sit out after a trade closes before a new entry is allowed. */
  cooldownBars?: number;
}

export interface ValidationIssue {
  path: string;
  message: string;
}

/**
 * Validates a strategy before it reaches the engine.
 *
 * Returns every problem found rather than throwing on the first, so a UI can
 * show the user their whole list of mistakes in one pass.
 */
export function validateStrategy(strategy: Strategy): ValidationIssue[] {
  const issues: ValidationIssue[] = [];
  const ids = new Set<string>();

  strategy.indicators.forEach((spec, index) => {
    if (!spec.id) {
      issues.push({ path: `indicators[${index}].id`, message: "Indicator needs an id" });
      return;
    }
    if (ids.has(spec.id)) {
      issues.push({ path: `indicators[${index}].id`, message: `Duplicate indicator id "${spec.id}"` });
    }
    ids.add(spec.id);

    if (spec.type === "macd" && spec.fast >= spec.slow) {
      issues.push({
        path: `indicators[${index}]`,
        message: `MACD fast period (${spec.fast}) must be less than slow (${spec.slow})`,
      });
    }
  });

  if (!strategy.long && !strategy.short) {
    issues.push({ path: "long/short", message: "Strategy must define at least one side to trade" });
  }

  const checkCondition = (condition: Condition, path: string): void => {
    switch (condition.type) {
      case "and":
      case "or":
        if (condition.children.length === 0) {
          issues.push({ path, message: `"${condition.type}" needs at least one child condition` });
        }
        condition.children.forEach((child, i) => checkCondition(child, `${path}.children[${i}]`));
        return;
      case "not":
        checkCondition(condition.child, `${path}.child`);
        return;
      case "always":
        return;
      default: {
        for (const [side, operand] of [
          ["left", condition.left],
          ["right", condition.right],
        ] as const) {
          if (operand.kind === "indicator" && !ids.has(operand.id)) {
            issues.push({ path: `${path}.${side}`, message: `Unknown indicator "${operand.id}"` });
          }
        }
      }
    }
  };

  if (strategy.long) checkCondition(strategy.long.entry, "long.entry");
  if (strategy.long?.exit) checkCondition(strategy.long.exit, "long.exit");
  if (strategy.short) checkCondition(strategy.short.entry, "short.entry");
  if (strategy.short?.exit) checkCondition(strategy.short.exit, "short.exit");

  const checkAtrRef = (spec: StopSpec | TargetSpec | undefined, path: string): void => {
    if (spec?.mode !== "atr") return;
    if (!ids.has(spec.atrId)) {
      issues.push({ path: `${path}.atrId`, message: `Unknown indicator "${spec.atrId}"` });
      return;
    }
    const referenced = strategy.indicators.find(i => i.id === spec.atrId);
    if (referenced && referenced.type !== "atr") {
      issues.push({
        path: `${path}.atrId`,
        message: `"${spec.atrId}" is a ${referenced.type}, not an atr — distance would be measured in the wrong units`,
      });
    }
  };

  checkAtrRef(strategy.stopLoss, "stopLoss");
  checkAtrRef(strategy.takeProfit, "takeProfit");
  checkAtrRef(strategy.trailingStop, "trailingStop");

  // These two combinations are unsatisfiable rather than merely odd: both need a
  // stop distance to compute against, and there is nothing sensible to fall back to.
  if (strategy.takeProfit?.mode === "riskReward" && !strategy.stopLoss) {
    issues.push({
      path: "takeProfit",
      message: "riskReward target needs a stopLoss to measure risk against",
    });
  }
  if (strategy.sizing.mode === "riskPercent" && !strategy.stopLoss) {
    issues.push({
      path: "sizing",
      message: "riskPercent sizing needs a stopLoss — without one the risk per trade is undefined",
    });
  }
  if (strategy.sizing.mode === "riskPercent" && strategy.sizing.percent <= 0) {
    issues.push({ path: "sizing.percent", message: "Risk percent must be greater than 0" });
  }
  if (strategy.sizing.mode === "fixedLot" && strategy.sizing.lots <= 0) {
    issues.push({ path: "sizing.lots", message: "Lot size must be greater than 0" });
  }

  if (strategy.sessionUtc) {
    const { startHour, endHour } = strategy.sessionUtc;
    for (const [name, hour] of [
      ["startHour", startHour],
      ["endHour", endHour],
    ] as const) {
      if (!Number.isInteger(hour) || hour < 0 || hour > 23) {
        issues.push({ path: `sessionUtc.${name}`, message: "Hour must be an integer between 0 and 23" });
      }
    }
  }

  return issues;
}
