/**
 * Pine Script v5 export.
 *
 * Translates a `Strategy` into a TradingView strategy script, so a result found
 * here can be checked on a real chart rather than taken on faith.
 *
 * The translation aims to preserve the engine's execution semantics, which
 * mostly line up with Pine's defaults:
 *
 * - Pine evaluates on bar close and fills at the next bar's open when
 *   `process_orders_on_close` is false. That is exactly this engine's model, so
 *   the default is left alone.
 * - `pyramiding=0` matches the one-position-at-a-time rule.
 * - Stop distances are captured on the SIGNAL bar and applied to the actual
 *   fill price via `strategy.position_avg_price`, mirroring how the engine
 *   sizes risk from information available before the entry bar opens.
 *
 * Where the two genuinely differ, the generated script says so in a header
 * comment rather than quietly diverging.
 */

import type {
  Condition,
  IndicatorSpec,
  Operand,
  StopSpec,
  Strategy,
  TargetSpec,
} from "../engine/strategy";
import type { CostModel, Instrument } from "../engine/types";

export interface PineOptions {
  instrument: Instrument;
  costs: CostModel;
  initialCapital: number;
}

export function strategyToPine(strategy: Strategy, options: PineOptions): string {
  const emitter = new PineEmitter(strategy, options);
  return emitter.emit();
}

class PineEmitter {
  /** Maps an indicator spec id to the Pine expression that yields its value. */
  private readonly expressions = new Map<string, string>();
  private readonly declarations: string[] = [];
  /** Tuple-returning calls already emitted, keyed by their arguments. */
  private readonly emittedCalls = new Set<string>();
  private readonly notes: string[] = [];

  constructor(
    private readonly strategy: Strategy,
    private readonly options: PineOptions,
  ) {}

  emit(): string {
    for (const spec of this.strategy.indicators) this.declareIndicator(spec);

    const longEntry = this.strategy.long ? this.condition(this.strategy.long.entry) : null;
    const longExit = this.strategy.long?.exit ? this.condition(this.strategy.long.exit) : null;
    const shortEntry = this.strategy.short ? this.condition(this.strategy.short.entry) : null;
    const shortExit = this.strategy.short?.exit ? this.condition(this.strategy.short.exit) : null;

    const lines: string[] = [];
    lines.push("//@version=5");
    lines.push(...this.header());
    lines.push("");
    lines.push(this.strategyCall());
    lines.push("");

    lines.push("// ── Indicators ──────────────────────────────────────────────");
    lines.push(...this.declarations);
    lines.push("");

    lines.push("// ── Risk distances ──────────────────────────────────────────");
    lines.push(`stopDistance = ${this.stopDistanceExpression(this.strategy.stopLoss)}`);
    lines.push(`targetDistance = ${this.targetDistanceExpression(this.strategy.takeProfit)}`);
    if (this.strategy.trailingStop) {
      lines.push(`trailDistance = ${this.stopDistanceExpression(this.strategy.trailingStop)}`);
    }
    lines.push("");

    lines.push("// ── Entry filters ───────────────────────────────────────────");
    lines.push(this.filterExpression());
    lines.push("");

    lines.push("// ── Signals ─────────────────────────────────────────────────");
    lines.push(`longSignal  = ${longEntry ?? "false"}`);
    lines.push(`shortSignal = ${shortEntry ?? "false"}`);
    if (longExit) lines.push(`longExitSignal  = ${longExit}`);
    if (shortExit) lines.push(`shortExitSignal = ${shortExit}`);
    lines.push("");

    lines.push(...this.executionBlock());

    if (this.notes.length > 0) {
      lines.push("");
      lines.push("// ── Notes ───────────────────────────────────────────────────");
      for (const note of this.notes) lines.push(`// ${note}`);
    }

    lines.push("");
    lines.push(...this.plotting());

    return lines.join("\n");
  }

  private header(): string[] {
    const { costs } = this.options;
    return [
      `// ${this.strategy.name}`,
      this.strategy.description ? `// ${this.strategy.description}` : "//",
      "//",
      "// Generated by Strategy Lab. Orders fill at the next bar's open, matching",
      "// the backtest that produced these parameters.",
      "//",
      "// Two things will not match a Strategy Lab run exactly:",
      "//   1. TradingView applies commission and slippage with its own rounding,",
      `//      and this script sets them from the backtest (${costs.spreadPips} pip spread,`,
      `//      ${costs.commissionPerLotPerSide} per lot per side, ${costs.slippagePips} pip slippage).`,
      "//   2. When a single bar touches both stop and target, Strategy Lab assumes",
      "//      the stop filled first. TradingView resolves this from its own",
      "//      intrabar assumption, so ambiguous bars can differ.",
    ];
  }

  private strategyCall(): string {
    const { instrument, costs, initialCapital } = this.options;
    // Spread is charged as commission per side in TradingView's model; half the
    // spread on each fill is the same total cost the engine applies.
    const spreadCost = (costs.spreadPips * instrument.pipSize) / 2;

    return [
      `strategy("${escapeString(this.strategy.name)}", overlay=true,`,
      `     initial_capital=${initialCapital},`,
      "     default_qty_type=strategy.fixed,",
      "     pyramiding=0,",
      "     calc_on_every_tick=false,",
      "     process_orders_on_close=false,",
      `     slippage=${Math.max(0, Math.round(costs.slippagePips))},`,
      `     commission_type=strategy.commission.cash_per_contract,`,
      `     commission_value=${(costs.commissionPerLotPerSide / instrument.contractSize + spreadCost).toPrecision(6)})`,
    ].join("\n");
  }

  private declareIndicator(spec: IndicatorSpec): void {
    const name = sanitize(spec.id);

    switch (spec.type) {
      case "sma":
        this.declare(name, `ta.sma(${spec.source ?? "close"}, ${spec.period})`, spec.id);
        return;
      case "ema":
        this.declare(name, `ta.ema(${spec.source ?? "close"}, ${spec.period})`, spec.id);
        return;
      case "rsi":
        this.declare(name, `ta.rsi(${spec.source ?? "close"}, ${spec.period})`, spec.id);
        return;
      case "atr":
        this.declare(name, `ta.atr(${spec.period})`, spec.id);
        return;
      case "highest":
        this.declare(name, `ta.highest(${spec.source ?? "high"}, ${spec.period})`, spec.id);
        return;
      case "lowest":
        this.declare(name, `ta.lowest(${spec.source ?? "low"}, ${spec.period})`, spec.id);
        return;

      case "adx":
      case "plusDI":
      case "minusDI": {
        // One ta.dmi call supplies all three; emit it once per period.
        const callKey = `dmi_${spec.period}`;
        if (!this.emittedCalls.has(callKey)) {
          this.emittedCalls.add(callKey);
          this.declarations.push(
            `[${callKey}_plus, ${callKey}_minus, ${callKey}_adx] = ta.dmi(${spec.period}, ${spec.period})`,
          );
        }
        const suffix = spec.type === "adx" ? "adx" : spec.type === "plusDI" ? "plus" : "minus";
        this.expressions.set(spec.id, `${callKey}_${suffix}`);
        return;
      }

      case "macd": {
        const callKey = `macd_${spec.fast}_${spec.slow}_${spec.signal}`;
        if (!this.emittedCalls.has(callKey)) {
          this.emittedCalls.add(callKey);
          this.declarations.push(
            `[${callKey}_line, ${callKey}_signal, ${callKey}_hist] = ta.macd(${spec.source ?? "close"}, ${spec.fast}, ${spec.slow}, ${spec.signal})`,
          );
        }
        const suffix = spec.output === "macd" ? "line" : spec.output === "signal" ? "signal" : "hist";
        this.expressions.set(spec.id, `${callKey}_${suffix}`);
        return;
      }

      case "bbands": {
        const callKey = `bb_${spec.period}_${String(spec.stdDev).replace(".", "p")}`;
        if (!this.emittedCalls.has(callKey)) {
          this.emittedCalls.add(callKey);
          this.declarations.push(
            `[${callKey}_middle, ${callKey}_upper, ${callKey}_lower] = ta.bb(${spec.source ?? "close"}, ${spec.period}, ${spec.stdDev})`,
          );
        }
        this.expressions.set(spec.id, `${callKey}_${spec.output}`);
        return;
      }

      case "stoch": {
        const callKey = `stoch_${spec.kPeriod}_${spec.smooth}_${spec.dPeriod}`;
        if (!this.emittedCalls.has(callKey)) {
          this.emittedCalls.add(callKey);
          this.declarations.push(
            `${callKey}_k = ta.sma(ta.stoch(close, high, low, ${spec.kPeriod}), ${spec.smooth})`,
          );
          this.declarations.push(`${callKey}_d = ta.sma(${callKey}_k, ${spec.dPeriod})`);
        }
        this.expressions.set(spec.id, `${callKey}_${spec.output}`);
        return;
      }

      case "supertrend": {
        const callKey = `st_${spec.period}_${String(spec.multiplier).replace(".", "p")}`;
        if (!this.emittedCalls.has(callKey)) {
          this.emittedCalls.add(callKey);
          this.declarations.push(`[${callKey}_line, ${callKey}_tvdir] = ta.supertrend(${spec.multiplier}, ${spec.period})`);
          // TradingView returns -1 for an UPTREND. Strategy Lab uses +1 for up,
          // so the sign is flipped here; without this every long and short
          // condition would be inverted on the chart.
          this.declarations.push(`${callKey}_direction = -${callKey}_tvdir`);
        }
        this.expressions.set(spec.id, `${callKey}_${spec.output}`);
        return;
      }

      default: {
        const unreachable: never = spec;
        throw new Error(`Cannot export indicator to Pine: ${JSON.stringify(unreachable)}`);
      }
    }
  }

  private declare(name: string, expression: string, specId: string): void {
    this.declarations.push(`${name} = ${expression}`);
    this.expressions.set(specId, name);
  }

  private condition(condition: Condition): string {
    switch (condition.type) {
      case "always":
        return "true";
      case "and":
        return `(${condition.children.map(child => this.condition(child)).join(" and ")})`;
      case "or":
        return `(${condition.children.map(child => this.condition(child)).join(" or ")})`;
      case "not":
        return `not (${this.condition(condition.child)})`;
      case "gt":
        return `${this.operand(condition.left)} > ${this.operand(condition.right)}`;
      case "gte":
        return `${this.operand(condition.left)} >= ${this.operand(condition.right)}`;
      case "lt":
        return `${this.operand(condition.left)} < ${this.operand(condition.right)}`;
      case "lte":
        return `${this.operand(condition.left)} <= ${this.operand(condition.right)}`;
      case "crossesAbove":
        return `ta.crossover(${this.operand(condition.left)}, ${this.operand(condition.right)})`;
      case "crossesBelow":
        return `ta.crossunder(${this.operand(condition.left)}, ${this.operand(condition.right)})`;
    }
  }

  private operand(operand: Operand): string {
    switch (operand.kind) {
      case "const":
        return String(operand.value);
      case "price":
        return operand.field;
      case "indicator": {
        const expression = this.expressions.get(operand.id);
        if (!expression) throw new Error(`Indicator "${operand.id}" is referenced but never declared`);
        return expression;
      }
    }
  }

  private stopDistanceExpression(spec: StopSpec | undefined): string {
    if (!spec) return "na";
    switch (spec.mode) {
      case "pips":
        return String(spec.value * this.options.instrument.pipSize);
      case "percent":
        return `close * ${spec.value / 100}`;
      case "atr": {
        const expression = this.expressions.get(spec.atrId);
        if (!expression) throw new Error(`Stop references undeclared ATR "${spec.atrId}"`);
        return `${expression} * ${spec.multiple}`;
      }
    }
  }

  private targetDistanceExpression(spec: TargetSpec | undefined): string {
    if (!spec) return "na";
    if (spec.mode === "riskReward") return `stopDistance * ${spec.ratio}`;
    return this.stopDistanceExpression(spec);
  }

  private filterExpression(): string {
    const clauses: string[] = [];

    if (this.strategy.sessionUtc) {
      const { startHour, endHour } = this.strategy.sessionUtc;
      const hour = 'hour(time, "UTC")';
      clauses.push(
        startHour <= endHour
          ? `(${hour} >= ${startHour} and ${hour} < ${endHour})`
          : `(${hour} >= ${startHour} or ${hour} < ${endHour})`,
      );
      this.notes.push(
        "The session filter is applied to the SIGNAL bar here. Strategy Lab applies it to the bar the order fills on, so entries at a session boundary can differ by one bar.",
      );
    }

    if (this.strategy.cooldownBars !== undefined) {
      clauses.push(`(na(barsSinceExit) or barsSinceExit > ${this.strategy.cooldownBars})`);
    }

    return `entryFilter = ${clauses.length > 0 ? clauses.join(" and ") : "true"}`;
  }

  private executionBlock(): string[] {
    const lines: string[] = [];
    const { sizing } = this.strategy;

    lines.push("// ── Execution ───────────────────────────────────────────────");
    lines.push("var float riskDistance = na");
    lines.push("var float rewardDistance = na");
    if (this.strategy.trailingStop) lines.push("var float trailStop = na");
    if (this.strategy.cooldownBars !== undefined) lines.push("var int barsSinceExit = na");
    if (this.strategy.maxBarsInTrade !== undefined) lines.push("var int barsInTrade = 0");
    lines.push("");

    if (this.strategy.cooldownBars !== undefined) {
      lines.push("if strategy.position_size == 0 and not na(barsSinceExit)");
      lines.push("    barsSinceExit := barsSinceExit + 1");
      lines.push("");
    }

    // Size so the stop costs exactly the configured risk, matching the engine.
    const qty =
      sizing.mode === "fixedLot"
        ? String(sizing.lots * this.options.instrument.contractSize)
        : `(strategy.equity * ${sizing.percent / 100}) / riskDistance`;

    lines.push("flat = strategy.position_size == 0");
    lines.push("");
    lines.push("if longSignal and flat and entryFilter");
    lines.push("    riskDistance := stopDistance");
    lines.push("    rewardDistance := targetDistance");
    if (this.strategy.trailingStop) lines.push("    trailStop := na");
    if (this.strategy.maxBarsInTrade !== undefined) lines.push("    barsInTrade := 0");
    lines.push(`    strategy.entry("Long", strategy.long, qty=${qty})`);
    lines.push("");
    lines.push("if shortSignal and flat and entryFilter");
    lines.push("    riskDistance := stopDistance");
    lines.push("    rewardDistance := targetDistance");
    if (this.strategy.trailingStop) lines.push("    trailStop := na");
    if (this.strategy.maxBarsInTrade !== undefined) lines.push("    barsInTrade := 0");
    lines.push(`    strategy.entry("Short", strategy.short, qty=${qty})`);
    lines.push("");

    if (this.strategy.trailingStop) {
      lines.push("// Trails from the bar CLOSE and only ever tightens, as the engine does.");
      lines.push("if strategy.position_size > 0");
      lines.push("    candidate = close - trailDistance");
      lines.push("    trailStop := na(trailStop) ? candidate : math.max(trailStop, candidate)");
      lines.push("if strategy.position_size < 0");
      lines.push("    candidate = close + trailDistance");
      lines.push("    trailStop := na(trailStop) ? candidate : math.min(trailStop, candidate)");
      lines.push("");
    }

    const longStop = this.strategy.trailingStop
      ? "math.max(nz(trailStop, strategy.position_avg_price - riskDistance), strategy.position_avg_price - riskDistance)"
      : "strategy.position_avg_price - riskDistance";
    const shortStop = this.strategy.trailingStop
      ? "math.min(nz(trailStop, strategy.position_avg_price + riskDistance), strategy.position_avg_price + riskDistance)"
      : "strategy.position_avg_price + riskDistance";

    lines.push("if strategy.position_size > 0");
    lines.push(`    strategy.exit("Long exit", from_entry="Long", stop=${longStop}${
      this.strategy.takeProfit ? ", limit=strategy.position_avg_price + rewardDistance" : ""
    })`);
    lines.push("if strategy.position_size < 0");
    lines.push(`    strategy.exit("Short exit", from_entry="Short", stop=${shortStop}${
      this.strategy.takeProfit ? ", limit=strategy.position_avg_price - rewardDistance" : ""
    })`);
    lines.push("");

    if (this.strategy.long?.exit) {
      lines.push('if strategy.position_size > 0 and longExitSignal');
      lines.push('    strategy.close("Long")');
    }
    if (this.strategy.short?.exit) {
      lines.push('if strategy.position_size < 0 and shortExitSignal');
      lines.push('    strategy.close("Short")');
    }

    if (this.strategy.maxBarsInTrade !== undefined) {
      lines.push("");
      lines.push("if strategy.position_size != 0");
      lines.push("    barsInTrade := barsInTrade + 1");
      lines.push(`    if barsInTrade >= ${this.strategy.maxBarsInTrade}`);
      lines.push('        strategy.close_all("Time stop")');
    }

    if (this.strategy.cooldownBars !== undefined) {
      lines.push("");
      lines.push("if strategy.position_size == 0 and strategy.position_size[1] != 0");
      lines.push("    barsSinceExit := 0");
    }

    return lines;
  }

  private plotting(): string[] {
    const lines = ["// ── Plots ───────────────────────────────────────────────────"];

    for (const spec of this.strategy.indicators) {
      const expression = this.expressions.get(spec.id);
      if (!expression) continue;
      // Only overlay indicators that live on the price scale; oscillators would
      // flatten the chart if plotted against price.
      const onPrice =
        spec.type === "sma" ||
        spec.type === "ema" ||
        spec.type === "highest" ||
        spec.type === "lowest" ||
        spec.type === "bbands" ||
        (spec.type === "supertrend" && spec.output === "line");
      if (!onPrice) continue;
      lines.push(`plot(${expression}, "${escapeString(spec.id)}")`);
    }

    if (lines.length === 1) lines.push("// (no price-scale indicators to plot)");
    return lines;
  }
}

/** Pine identifiers allow letters, digits and underscore, and cannot lead with a digit. */
function sanitize(id: string): string {
  const cleaned = id.replace(/[^a-zA-Z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

function escapeString(value: string): string {
  return value.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}
